In [29]:
import pandas as pd
import matplotlib as mp
import sklearn as sk

In [30]:
path = '/Users/amalkadri/Documents/CodeBook/ECO395M/'
path_abia = 'data/ABIA.csv'
path_olympics = 'data/olympics_top20.csv'
path_sclass = 'data/sclass.csv'

abia = pd.read_csv(path+path_abia).fillna(0)
olympics = pd.read_csv(path+path_olympics)
sclass = pd.read_csv(path+path_sclass)
abia

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,1,2,120.0,1935,309.0,2130,9E,5746,...,3.0,18.0,0,0,0,339.0,0.0,0.0,0.0,0.0
1,2008,1,1,2,555.0,600,826.0,835,AA,1614,...,7.0,11.0,0,0,0,0.0,0.0,0.0,0.0,0.0
2,2008,1,1,2,600.0,600,728.0,729,YV,2883,...,7.0,16.0,0,0,0,0.0,0.0,0.0,0.0,0.0
3,2008,1,1,2,601.0,605,727.0,750,9E,5743,...,4.0,12.0,0,0,0,0.0,0.0,0.0,0.0,0.0
4,2008,1,1,2,601.0,600,654.0,700,AA,1157,...,5.0,10.0,0,0,0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99255,2008,12,31,3,2109.0,2100,2158.0,2157,CO,1533,...,5.0,18.0,0,0,0,0.0,0.0,0.0,0.0,0.0
99256,2008,12,31,3,2124.0,2123,2246.0,2300,9E,5805,...,4.0,22.0,0,0,0,0.0,0.0,0.0,0.0,0.0
99257,2008,12,31,3,2327.0,2325,9.0,20,AA,1532,...,5.0,7.0,0,0,0,0.0,0.0,0.0,0.0,0.0
99258,2008,12,31,3,0.0,1220,0.0,1711,B6,1264,...,0.0,0.0,1,B,0,0.0,0.0,0.0,0.0,0.0
99259,2008,12,31,3,0.0,1300,0.0,1617,B6,1065,...,0.0,0.0,1,B,0,0.0,0.0,0.0,0.0,0.0